CREATE DATABASE IF NOT EXISTS RESTAURANTDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE RESTAURANTDB;

-- BEGIN ESTRUCTURA DE BASE DE DATOS

CREATE TABLE BEVERAGE_TYPE(
	ID INT(11) AUTO_INCREMENT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	CONSTRAINT PK_BEVERAGE_TYPE PRIMARY KEY(ID),
	CONSTRAINT UQ_BEVERAGE_TYPE_NAME UNIQUE(NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE BEVERAGE(
	ID INT(11) AUTO_INCREMENT NOT NULL,
	NAME VARCHAR(150) NOT NULL,
	PRICE DECIMAL(6,2) NOT NULL,
	BTYPE INT(11) NOT NULL,
	CONSTRAINT PK_BEVERAGE PRIMARY KEY(ID),
	CONSTRAINT FK_BEVERAGE_TYPE FOREIGN KEY(BTYPE) REFERENCES BEVERAGE_TYPE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE DISH_TYPE(
	ID INT(11) AUTO_INCREMENT NOT NULL,
	NAME VARCHAR(80) NOT NULL,
	CONSTRAINT PK_DISH_TYPE PRIMARY KEY(ID),
	CONSTRAINT UQ_DISH_TYPE_NAME UNIQUE(NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE DISH(
	ID INT(11) AUTO_INCREMENT NOT NULL,
	NAME VARCHAR(80) NOT NULL,
	DESCRIPTION VARCHAR(140) DEFAULT NULL,
	PRICE DECIMAL(6,2) NOT NULL,
	DTYPE INT(11) NOT NULL,
	CONSTRAINT PK_DISH PRIMARY KEY(ID),
	CONSTRAINT UQ_DISH_NAME UNIQUE(NAME),
	CONSTRAINT FK_DISH_TYPE FOREIGN KEY(DTYPE) REFERENCES DISH_TYPE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE SALE(
	ID INT(11) AUTO_INCREMENT NOT NULL,
	SALE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	AMOUNT DECIMAL(6,2) NOT NULL,
	PAYMENT_TYPE ENUM('PAYPAL', 'BIZUM', 'CARD', 'CASH') NOT NULL DEFAULT 'CASH',
	CONSUMPTION TEXT NOT NULL,
	CONSTRAINT PK_SALE PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- END ESTRUCTURA DE BASE DE DATOS

-- BEGIN INSERCIONES
-- Inserciones para la tabla BEVERAGE_TYPE
INSERT INTO RESTAURANTDB.BEVERAGE_TYPE (NAME) VALUES ('Soda');
INSERT INTO RESTAURANTDB.BEVERAGE_TYPE (NAME) VALUES ('Juice');
INSERT INTO RESTAURANTDB.BEVERAGE_TYPE (NAME) VALUES ('Beer');
INSERT INTO RESTAURANTDB.BEVERAGE_TYPE (NAME) VALUES ('Wine');
INSERT INTO RESTAURANTDB.BEVERAGE_TYPE (NAME) VALUES ('Water');

-- Inserciones para la tabla BEVERAGE
INSERT INTO RESTAURANTDB.BEVERAGE (NAME, PRICE, BTYPE) VALUES ('Coca Cola', 1.50, 1);
INSERT INTO RESTAURANTDB.BEVERAGE (NAME, PRICE, BTYPE) VALUES ('Orange Juice', 2.00, 2);
INSERT INTO RESTAURANTDB.BEVERAGE (NAME, PRICE, BTYPE) VALUES ('Heineken', 3.00, 3);
INSERT INTO RESTAURANTDB.BEVERAGE (NAME, PRICE, BTYPE) VALUES ('Red Wine', 4.50, 4);
INSERT INTO RESTAURANTDB.BEVERAGE (NAME, PRICE, BTYPE) VALUES ('Mineral Water', 1.00, 5);

-- Inserciones para la tabla DISH_TYPE
INSERT INTO RESTAURANTDB.DISH_TYPE (NAME) VALUES ('Appetizer');
INSERT INTO RESTAURANTDB.DISH_TYPE (NAME) VALUES ('Main Course');
INSERT INTO RESTAURANTDB.DISH_TYPE (NAME) VALUES ('Dessert');
INSERT INTO RESTAURANTDB.DISH_TYPE (NAME) VALUES ('Salad');
INSERT INTO RESTAURANTDB.DISH_TYPE (NAME) VALUES ('Soup');

-- Inserciones para la tabla DISH
INSERT INTO RESTAURANTDB.DISH (NAME, DESCRIPTION, PRICE, DTYPE) VALUES ('Bruschetta', 'Toasted bread with tomatoes', 5.50, 1);
INSERT INTO RESTAURANTDB.DISH (NAME, DESCRIPTION, PRICE, DTYPE) VALUES ('Steak', 'Grilled beef steak', 15.00, 2);
INSERT INTO RESTAURANTDB.DISH (NAME, DESCRIPTION, PRICE, DTYPE) VALUES ('Cheesecake', 'Creamy cheesecake', 6.00, 3);
INSERT INTO RESTAURANTDB.DISH (NAME, DESCRIPTION, PRICE, DTYPE) VALUES ('Caesar Salad', 'Salad with chicken and Caesar dressing', 7.50, 4);
INSERT INTO RESTAURANTDB.DISH (NAME, DESCRIPTION, PRICE, DTYPE) VALUES ('Tomato Soup', 'Fresh tomato soup', 4.50, 5);

-- Inserciones para la tabla SALE
INSERT INTO RESTAURANTDB.SALE (AMOUNT, PAYMENT_TYPE, CONSUMPTION) VALUES (23.50, 'CARD', '1 Bruschetta, 1 Steak, 1 Red Wine');
INSERT INTO RESTAURANTDB.SALE (AMOUNT, PAYMENT_TYPE, CONSUMPTION) VALUES (10.50, 'CASH', '1 Caesar Salad, 1 Mineral Water');
INSERT INTO RESTAURANTDB.SALE (AMOUNT, PAYMENT_TYPE, CONSUMPTION) VALUES (8.50, 'BIZUM', '1 Tomato Soup, 1 Coca Cola');
INSERT INTO RESTAURANTDB.SALE (AMOUNT, PAYMENT_TYPE, CONSUMPTION) VALUES (12.00, 'PAYPAL', '1 Cheesecake, 1 Orange Juice');
INSERT INTO RESTAURANTDB.SALE (AMOUNT, PAYMENT_TYPE, CONSUMPTION) VALUES (18.00, 'CARD', '1 Bruschetta, 1 Heineken, 1 Caesar Salad');

-- END INSERCIONES