FROM zookeeper:latest

# Establecer el puerto de Zookeeper
EXPOSE 2181 2888 3888

# Configuraciones adicionales
# ADD ejemplo.cfg /ruta/a/config

# Iniciar Zookeeper (esto ya está definido en la imagen oficial)
#CMD ["zkServer.sh", "start-foreground"]