server:
  port: 9000
  
spring:
  application:
    name: micro-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/rpjdcode/microservices-configuration
          search-paths: /config-data
          username: rpjdcode
          password: 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
