# Utiliza la última imagen oficial de Zipkin
FROM openzipkin/zipkin:latest

# Expone el puerto 9411 para acceso web y comunicación
EXPOSE 9411

# La imagen de Zipkin ya contiene un ENTRYPOINT que arranca el servidor Zipkin